module.exports = { 
  '1': { key: 'Annie', title: 'the Dark Child', name: 'Annie' },
  '2': { key: 'Olaf', title: 'the Berserker', name: 'Olaf' },
  '3': { key: 'Galio', title: 'the Sentinel\'s Sorrow', name: 'Galio' },
  '4': { key: 'TwistedFate', title: 'the Card Master', name: 'Twisted Fate' },
  '5': { key: 'XinZhao', title: 'the Seneschal of Demacia', name: 'Xin Zhao' },
  '6': { key: 'Urgot', title: 'the Headsman\'s Pride', name: 'Urgot' },
  '7': { key: 'Leblanc', title: 'the Deceiver', name: 'LeBlanc' },
  '8': { key: 'Vladimir', title: 'the Crimson Reaper', name: 'Vladimir' },
  '9': { key: 'FiddleSticks', title: 'the Harbinger of Doom', name: 'Fiddlesticks' },
  '10': { key: 'Kayle', title: 'The Judicator', name: 'Kayle' },
  '11': { key: 'MasterYi', title: 'the Wuju Bladesman', name: 'Master Yi' },
  '12': { key: 'Alistar', title: 'the Minotaur', name: 'Alistar' },
  '13': { key: 'Ryze', title: 'the Rogue Mage', name: 'Ryze' },
  '14': { key: 'Sion', title: 'The Undead Juggernaut', name: 'Sion' },
  '15': { key: 'Sivir', title: 'the Battle Mistress', name: 'Sivir' },
  '16': { key: 'Soraka', title: 'the Starchild', name: 'Soraka' },
  '17': { key: 'Teemo', title: 'the Swift Scout', name: 'Teemo' },
  '18': { key: 'Tristana', title: 'the Yordle Gunner', name: 'Tristana' },
  '19': { key: 'Warwick', title: 'the Blood Hunter', name: 'Warwick' },
  '20': { key: 'Nunu', title: 'the Yeti Rider', name: 'Nunu' },
  '21': { key: 'MissFortune', title: 'the Bounty Hunter', name: 'Miss Fortune' },
  '22': { key: 'Ashe', title: 'the Frost Archer', name: 'Ashe' },
  '23': { key: 'Tryndamere', title: 'the Barbarian King', name: 'Tryndamere' },
  '24': { key: 'Jax', title: 'Grandmaster at Arms', name: 'Jax' },
  '25': { key: 'Morgana', title: 'Fallen Angel', name: 'Morgana' },
  '26': { key: 'Zilean', title: 'the Chronokeeper', name: 'Zilean' },
  '27': { key: 'Singed', title: 'the Mad Chemist', name: 'Singed' },
  '28': { key: 'Evelynn', title: 'the Widowmaker', name: 'Evelynn' },
  '29': { key: 'Twitch', title: 'the Plague Rat', name: 'Twitch' },
  '30': { key: 'Karthus', title: 'the Deathsinger', name: 'Karthus' },
  '31': { key: 'Chogath', title: 'the Terror of the Void', name: 'Cho\'Gath' },
  '32': { key: 'Amumu', title: 'the Sad Mummy', name: 'Amumu' },
  '33': { key: 'Rammus', title: 'the Armordillo', name: 'Rammus' },
  '34': { key: 'Anivia', title: 'the Cryophoenix', name: 'Anivia' },
  '35': { key: 'Shaco', title: 'the Demon Jester', name: 'Shaco' },
  '36': { key: 'DrMundo', title: 'the Madman of Zaun', name: 'Dr. Mundo' },
  '37': { key: 'Sona', title: 'Maven of the Strings', name: 'Sona' },
  '38': { key: 'Kassadin', title: 'the Void Walker', name: 'Kassadin' },
  '39': { key: 'Irelia', title: 'the Will of the Blades', name: 'Irelia' },
  '40': { key: 'Janna', title: 'the Storm\'s Fury', name: 'Janna' },
  '41': { key: 'Gangplank', title: 'the Saltwater Scourge', name: 'Gangplank' },
  '42': { key: 'Corki', title: 'the Daring Bombardier', name: 'Corki' },
  '43': { key: 'Karma', title: 'the Enlightened One', name: 'Karma' },
  '44': { key: 'Taric', title: 'the Shield of Valoran', name: 'Taric' },
  '45': { key: 'Veigar', title: 'the Tiny Master of Evil', name: 'Veigar' },
  '48': { key: 'Trundle', title: 'the Troll King', name: 'Trundle' },
  '50': { key: 'Swain', title: 'the Master Tactician', name: 'Swain' },
  '51': { key: 'Caitlyn', title: 'the Sheriff of Piltover', name: 'Caitlyn' },
  '53': { key: 'Blitzcrank', title: 'the Great Steam Golem', name: 'Blitzcrank' },
  '54': { key: 'Malphite', title: 'Shard of the Monolith', name: 'Malphite' },
  '55': { key: 'Katarina', title: 'the Sinister Blade', name: 'Katarina' },
  '56': { key: 'Nocturne', title: 'the Eternal Nightmare', name: 'Nocturne' },
  '57': { key: 'Maokai', title: 'the Twisted Treant', name: 'Maokai' },
  '58': { key: 'Renekton', title: 'the Butcher of the Sands', name: 'Renekton' },
  '59': { key: 'JarvanIV', title: 'the Exemplar of Demacia', name: 'Jarvan IV' },
  '60': { key: 'Elise', title: 'the Spider Queen', name: 'Elise' },
  '61': { key: 'Orianna', title: 'the Lady of Clockwork', name: 'Orianna' },
  '62': { key: 'MonkeyKing', title: 'the Monkey King', name: 'Wukong' },
  '63': { key: 'Brand', title: 'the Burning Vengeance', name: 'Brand' },
  '64': { key: 'LeeSin', title: 'the Blind Monk', name: 'Lee Sin' },
  '67': { key: 'Vayne', title: 'the Night Hunter', name: 'Vayne' },
  '68': { key: 'Rumble', title: 'the Mechanized Menace', name: 'Rumble' },
  '69': { key: 'Cassiopeia', title: 'the Serpent\'s Embrace', name: 'Cassiopeia' },
  '72': { key: 'Skarner', title: 'the Crystal Vanguard', name: 'Skarner' },
  '74': { key: 'Heimerdinger', title: 'the Revered Inventor', name: 'Heimerdinger' },
  '75': { key: 'Nasus', title: 'the Curator of the Sands', name: 'Nasus' },
  '76': { key: 'Nidalee', title: 'the Bestial Huntress', name: 'Nidalee' },
  '77': { key: 'Udyr', title: 'the Spirit Walker', name: 'Udyr' },
  '78': { key: 'Poppy', title: 'Keeper of the Hammer', name: 'Poppy' },
  '79': { key: 'Gragas', title: 'the Rabble Rouser', name: 'Gragas' },
  '80': { key: 'Pantheon', title: 'the Artisan of War', name: 'Pantheon' },
  '81': { key: 'Ezreal', title: 'the Prodigal Explorer', name: 'Ezreal' },
  '82': { key: 'Mordekaiser', title: 'the Iron Revenant', name: 'Mordekaiser' },
  '83': { key: 'Yorick', title: 'the Gravedigger', name: 'Yorick' },
  '84': { key: 'Akali', title: 'the Fist of Shadow', name: 'Akali' },
  '85': { key: 'Kennen', title: 'the Heart of the Tempest', name: 'Kennen' },
  '86': { key: 'Garen', title: 'The Might of Demacia', name: 'Garen' },
  '89': { key: 'Leona', title: 'the Radiant Dawn', name: 'Leona' },
  '90': { key: 'Malzahar', title: 'the Prophet of the Void', name: 'Malzahar' },
  '91': { key: 'Talon', title: 'the Blade\'s Shadow', name: 'Talon' },
  '92': { key: 'Riven', title: 'the Exile', name: 'Riven' },
  '96': { key: 'KogMaw', title: 'the Mouth of the Abyss', name: 'Kog\'Maw' },
  '98': { key: 'Shen', title: 'the Eye of Twilight', name: 'Shen' },
  '99': { key: 'Lux', title: 'the Lady of Luminosity', name: 'Lux' },
  '101': { key: 'Xerath', title: 'the Magus Ascendant', name: 'Xerath' },
  '102': { key: 'Shyvana', title: 'the Half-Dragon', name: 'Shyvana' },
  '103': { key: 'Ahri', title: 'the Nine-Tailed Fox', name: 'Ahri' },
  '104': { key: 'Graves', title: 'the Outlaw', name: 'Graves' },
  '105': { key: 'Fizz', title: 'the Tidal Trickster', name: 'Fizz' },
  '106': { key: 'Volibear', title: 'the Thunder\'s Roar', name: 'Volibear' },
  '107': { key: 'Rengar', title: 'the Pridestalker', name: 'Rengar' },
  '110': { key: 'Varus', title: 'the Arrow of Retribution', name: 'Varus' },
  '111': { key: 'Nautilus', title: 'the Titan of the Depths', name: 'Nautilus' },
  '112': { key: 'Viktor', title: 'the Machine Herald', name: 'Viktor' },
  '113': { key: 'Sejuani', title: 'the Winter\'s Wrath', name: 'Sejuani' },
  '114': { key: 'Fiora', title: 'the Grand Duelist', name: 'Fiora' },
  '115': { key: 'Ziggs', title: 'the Hexplosives Expert', name: 'Ziggs' },
  '117': { key: 'Lulu', title: 'the Fae Sorceress', name: 'Lulu' },
  '119': { key: 'Draven', title: 'the Glorious Executioner', name: 'Draven' },
  '120': { key: 'Hecarim', title: 'the Shadow of War', name: 'Hecarim' },
  '121': { key: 'Khazix', title: 'the Voidreaver', name: 'Kha\'Zix' },
  '122': { key: 'Darius', title: 'the Hand of Noxus', name: 'Darius' },
  '126': { key: 'Jayce', title: 'the Defender of Tomorrow', name: 'Jayce' },
  '127': { key: 'Lissandra', title: 'the Ice Witch', name: 'Lissandra' },
  '131': { key: 'Diana', title: 'Scorn of the Moon', name: 'Diana' },
  '133': { key: 'Quinn', title: 'Demacia\'s Wings', name: 'Quinn' },
  '134': { key: 'Syndra', title: 'the Dark Sovereign', name: 'Syndra' },
  '136': { key: 'AurelionSol', title: 'The Star Forger', name: 'Aurelion Sol' },
  '143': { key: 'Zyra', title: 'Rise of the Thorns', name: 'Zyra' },
  '150': { key: 'Gnar', title: 'the Missing Link', name: 'Gnar' },
  '154': { key: 'Zac', title: 'the Secret Weapon', name: 'Zac' },
  '157': { key: 'Yasuo', title: 'the Unforgiven', name: 'Yasuo' },
  '161': { key: 'Velkoz', title: 'the Eye of the Void', name: 'Vel\'Koz' },
  '201': { key: 'Braum', title: 'the Heart of the Freljord', name: 'Braum' },
  '202': { key: 'Jhin', title: 'the Virtuoso', name: 'Jhin' },
  '203': { key: 'Kindred', title: 'The Eternal Hunters', name: 'Kindred' },
  '222': { key: 'Jinx', title: 'the Loose Cannon', name: 'Jinx' },
  '223': { key: 'TahmKench', title: 'the River King', name: 'Tahm Kench' },
  '236': { key: 'Lucian', title: 'the Purifier', name: 'Lucian' },
  '238': { key: 'Zed', title: 'the Master of Shadows', name: 'Zed' },
  '245': { key: 'Ekko', title: 'the Boy Who Shattered Time', name: 'Ekko' },
  '254': { key: 'Vi', title: 'the Piltover Enforcer', name: 'Vi' },
  '266': { key: 'Aatrox', title: 'the Darkin Blade', name: 'Aatrox' },
  '267': { key: 'Nami', title: 'the Tidecaller', name: 'Nami' },
  '268': { key: 'Azir', title: 'the Emperor of the Sands', name: 'Azir' },
  '412': { key: 'Thresh', title: 'the Chain Warden', name: 'Thresh' },
  '420': { key: 'Illaoi', title: 'the Kraken Priestess', name: 'Illaoi' },
  '421': { key: 'RekSai', title: 'the Void Burrower', name: 'Rek\'Sai' },
  '429': { key: 'Kalista', title: 'the Spear of Vengeance', name: 'Kalista' },
  '432': { key: 'Bard', title: 'the Wandering Caretaker', name: 'Bard' } }